### ISSUE TITLE
to do

### ISSUE THREAD

**Issue by chanchihiro** [nippoly/nippoly.github.io#2]
あとやること

- [x] モバイル対応
- [x]  cssのminify（最後）
- [x]  loading画面実装（最後のちょっと前）
- [x]  ディレクトリの移行？ディレクトリ管理(最後)
publicをこちらに残して、開発環境をnippolyに移籍
https://github.com/chanchihiro/nippoly　これ
- [x]  gifの二個目を変える
間に合わなそうだから今回は諦める
- [x]  リンク先の設定(最後に確認しながらやる)

**Comment by chanchihiro** [comment]
モバイル確認もヨロです

**Comment by chanchihiro** [comment]
主はPCなんで付け焼き刃です

**Comment by s11y** [comment]
開発環境の別リポジトリ用意するわ！これで！
https://github.com/nippoly/nippoly-landing-page

**Comment by chanchihiro** [comment]
明日直前に移行します！

**Comment by s11y** [comment]
gulp側でどうやってhtmlとかを生成してるかわからんからなんとも言えんけど、うまくわけたいね

**Comment by chanchihiro** [comment]
htmlは今回コンパイルしてない〜〜！cssとjsでしてるから直で対話しながらやりたい感ある。
privateできない...よね...

**Comment by s11y** [comment]
https://github.com/shinnn/gulp-gh-pages

なんかこんなのあったけど、使ってみたら？

**Comment by s11y** [comment]
これでうまくやれば2つのディレクトリを別々にgit管理して、ちょくちょくコンパイル通してgithub pagesのほうのリポジトリにプッシュしてみるのもいいと思う

**Comment by chanchihiro** [comment]
おお
めっちゃいい！やって見る

**Comment by chanchihiro** [comment]
あとリンク先とディレクトリ管理したらLPは出せそう

**Comment by chanchihiro** [comment]
クロスブラウザも確認しました（学校で）

**Comment by s11y** [comment]
🎉

**Comment by chanchihiro** [comment]
とりあえずおわた
