### ISSUE TITLE
GIFのリンク切れ

### ISSUE THREAD

**Issue by touyou** [nippoly/nippoly.github.io#3]
GIFが全てリンク切れを起こしている

# TO-DO
- [x] JavaScriptから動的に入れているパスを`../img/hoge.gif`から`img/hoge.gif`に変える
- [x] (Option) IDをunchiからstep-gifとかなんかもうちょい人目を気にしたものにする笑

**Comment by chanchihiro** [comment]
笑

**Comment by chanchihiro** [comment]
@touyou 
リンクの方、今gulpで起動してる？
gulpでやらないとpublicのbundleにコンパイルと収縮されないでリンク切れちゃうのかも！納品の時には多分このパスになるはず...！

**Comment by touyou** [comment]
http://nippoly.github.io/public
を見てる！

**Comment by chanchihiro** [comment]
わ！まじだ。なんでだろ

**Comment by touyou** [comment]
ようはGitHub PagesのまずURLもどうにかしなきゃいけないんだけど（設定で一番上のフォルダを設定できたかもしれないけどわからない）
今はpublic/index.htmlでページを表示するようになってて、そうするとそこから../imgっていうのはnippoly.github.io/imgってフォルダを参照することになるから当然ないわけで...

どっちにしてもindex.htmlからimgがどこにあるかでパスふらないとダメだと思う

**Comment by touyou** [comment]
てかやっぱりリポジトリの一番上の階層にindex.htmlある構成にしなきゃまずい気がする、自動的にリダイレクトさせてもいいけどどちらにしろ今のままだとURLがnippoly.github.io/publicになっちゃうし...

**Comment by chanchihiro** [comment]
そっかこれhtmlの方から参照するのか笑。jsから参照すると勘違いしてた〜

**Comment by chanchihiro** [comment]
なるほど〜！じゃあnipplyっていうリポジトリが謎にあるからそっちに開発環境写して、publicだけ最後にこっちに残そう！

**Comment by chanchihiro** [comment]
とりあえずgif修正doneっす
